### PR TITLE
ui/custom-metadata: Refactor taxonomy to use a single form submission flow

### LINKED ISSUE #2545: Custom metadata UI bug roundup
Results of PR smoke test: https://github.com/ethyca/fides/pull/2536#issuecomment-1423341630

**Main checks**
- [x] No errors seemed to be the API's fault. (No 500; validation errors were correct.)
- [x] With the feature flag (`customFields`) disabled, editing taxonomy entities still works.

**Functionality status**
- Defining custom lists
  - [x] Create
  - [x] Use for a field definition
- Defining custom fields
  - [x] Create single select
  - [x] Create multi select
  - [x] Cancel button warns about discarding changes
- [ ] "Show in forms and reports"
  - How do we verify this?
- Using single select
  - [x] Initial selection
  - [ ] Removing selection
  - [ ] Changing selection
  - [ ] Initial load when data has been saved
- Using multi select
  - [x] Initial selection
  - [ ] Removing selection
  - [ ] Changing selection
  - [ ] Initial load when data has been saved
- [ ] When there are multiple metadata fields
- [ ] Switching between taxonomy entities
- [x] Switching between resource types
  - Does seem to reset the form correctly

**Bugs**
- On initial load the spinners don't go away
- The requests 404 because no fields have been added to a category
  - The API is correct to return 404
  - The UI needs to understand the "nothing exists yet" case
  - Probably causes the spinners problem
- Clicking "edit" on another category doesn't update the custom fields form
  - Inconsistent
  - Might only happen if you made change in the form
  - Wait, unless custom fields are supposed to show up for all data categories? In which case the problem is that the form sometimes forgets which fields to show.
- Removing a item from the field select list doesn't remove the item
  - But if you "Update entity" and refresh the page it will have been saved
- Clicking "save" doesn't close the add field modal
- Clicking "save" doesn't refresh the custom field form
- Having two fields backed by the same select list causes the form fields to get mixed up
  - This should be fine. They should have the same list of choices, but the values should be independent.
  - Actually, it might not matter which custom list the fields use. Values seem to attach to the wrong fields sometimes regardless.
  - Can result in API error response because a single select was passed an array or a multi was passed a string
    - http://localhost:3000/api/v1/plus/custom-metadata/custom-field
    ```json
    {"custom_field_definition_id":"plu_a5f493f8-cbb7-435d-a94c-f28ec281f4c1","id":"plu_5ee31d1d-7ed2-44fe-9cfb-6970295f0d39","resource_id":"system.operations","value":["a"]}
    ```
    ```json
    {"detail":"The value for the specified custom field type must be a string"}
    ```
- Fields reorder after updating their values
- "Update" button stays disabled after request completed
- Form fields flicker after update.
- Can't update the values of any fields after initially setting them (couldn't tell if this was captured elsewhere here)

### PR DESCRIPTION
**Pull request by ssangervasi**
Closes #2545

### Code Changes

* This is a large refactor to get taxonomy and custom fields working together. See description below and my line comments.

### Steps to Confirm

* [ ] Cypress tests!
* [ ] From various taxonomy tabs
    * [ ] Assign custom fields
    * [ ] Single-select
        * [ ] Initial selection
        * [ ] Change selection
        * [ ] Clear selection
        * [ ] See value on reload
    * [ ] Multi-select
        * [ ] Initial selection
        * [ ] Change selection
        * [ ] Clear selection
        * [ ] See value on reload
* [ ] Those steps, but from the "Describe system" tab

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
    - Might be spun out: https://github.com/ethyca/fides/issues/2545#issuecomment-1429021292
    - https://github.com/ethyca/fides/issues/2612
* [ ] Update `CHANGELOG.md`

### Description Of Changes

* [x] I'm tired. When I finish my self-review I'll check this box.

### CODE REVIEW

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+  const { options } = allowList;
+
+  const [, meta, helpers] = useField({ name });
+
+  // This is a bit of a hack to set the initial value of the selector based on the CustomField
+  // returned by the API (if any). The "correct" way to do this would be to have the `initialValues`
+  // passed to `Formik` include the API values mapped by definition ID. However, because custom
+  // fields are so dynamic and depend on multiple API calls, mixing that logic into the (already
+  // complex) taxonomy form initialization isn't feasible for now. Those values are created by:
+  // src/features/taxonomy/hooks.tsx.
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx:36]: Now that I've refactored the taxonomy hooks anyway, it's possible the initial values could get populated in the correct way. I couldn't figure out a good way to do that yet though.

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx [hunk 2]
```diff
@@ -1,169 +1,41 @@
...
-  resourceId,
+export const CustomFieldsList = ({
+  resourceFidesKey,
   resourceType,
 }: CustomFieldsListProps) => {
-  const { errorAlert, successAlert } = useAlert();
-
-  const { flags, plus } = useFeatures();
-  const skip = !(flags.customFields && plus);
-  const [isLoading, setIsLoading] = useState(!skip);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx:39]: The loading state now comes from the queries/mutations themselves.

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx [hunk 3]
```diff
@@ -1,169 +1,41 @@
...
-  const [upsertCustomField] = useUpsertCustomFieldMutation();
-
-  // Reference parent Formik context
   const {
-    isSubmitting,
-    setSubmitting,
-    values: formValues,
-  } = useFormikContext();
-
-  const editCustomFieldList = useMemo(() => {
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx:57]: The logic of these memoized bits has been extracted to a hook: `useCustomFields`. It's also been restructured, which I'll comment on that file.

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx [hunk 4]
```diff
@@ -1,169 +1,41 @@
...
+  } = useCustomFields({
+    resourceFidesKey,
+    resourceType,
+  });
 
-  useEffect(() => {
-    if (isSubmitting && (formValues as any).customFields) {
-      handleSubmit(formValues as FormValues);
-    }
-  }, [formValues, handleSubmit, isSubmitting]);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx:161]: **Key change**
A major motivation for integrating custom fields onto the taxonomy hooks is to avoid this monkey patching of Formik's submission state. Formik has good handling of async (promise) submission, so moving the logic to a single chain of API calls removes the need to do complex state-timing debugging.

File: clients/admin-ui/src/features/common/custom-fields/helpers.ts [hunk 5]
```diff
@@ -6,3 +8,8 @@ export const getResourceType = (valueOrLabel: string) =>
   RESOURCE_TYPE_OPTIONS.find(
     (option) => option.value === valueOrLabel || option.label === valueOrLabel
   )?.value ?? ResourceTypes.SYSTEM;
+
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/helpers.ts:11]: Oh, looks like `getResourceType` can be deleted now.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+export const useCustomFields = ({
+  resourceFidesKey,
+  resourceType,
+}: UseCustomFieldsOptions) => {
+  const { errorAlert, successAlert } = useAlert();
+  const { flags, plus } = useFeatures();
+  const isEnabled = flags.customFields && plus;
+
+  // eslint-disable-next-line react-hooks/exhaustive-deps
+  const queryFidesKey = useMemo(() => resourceFidesKey ?? "", []);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/hooks.ts:31]: I mean to put a code comment here explaining that this prevents re-querying for a custom fields that will just 404.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts [hunk 7]
```diff
@@ -0,0 +1,191 @@
...
+
+      // This will be undefined if the form never rendered a `CustomFieldList` that would assign
+      // form values.
+      if (!definitionIdToCustomFieldValue) {
+        return;
+      }
+
+      try {
+        // This would be a lot simpler (and more efficient) if the API had an endpoint for updating
+        // all the metadata associated with a field, including deleting options that weren't passed.
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/hooks.ts:130]: Should I create an issue for this?

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts [hunk 8]
```diff
@@ -0,0 +1,191 @@
...
+            if (
+              value === undefined ||
+              value === "" ||
+              (Array.isArray(value) && value.length === 0)
+            ) {
+              if (!customField?.id) {
+                return undefined;
+              }
+
+              return deleteCustomFieldMutationTrigger(customField);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/hooks.ts:145]: The previous submission code didn't have the ability to delete custom fields. I think the API forbids setting the field to an empty string, which makes sense because that isn't an allowed value. So we have to delete the field assignment if the value is blank.

File: clients/admin-ui/src/features/common/custom-fields/types.ts [hunk 9]
```diff
@@ -9,3 +14,33 @@ export interface CustomFieldWithIdExtended extends CustomFieldWithId {
 export interface Tab extends TabData {
   submitButtonText: string;
 }
+
+export interface CustomFieldDefinitionExisting
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/custom-fields/types.ts:18]: `...Existing` is the best I could think of. The `...WithId` type allows `id` to be `undefined` which isn't useful in most of the code.

File: clients/admin-ui/src/features/common/form/inputs.tsx [hunk 10]
```diff
@@ -169,6 +169,7 @@ const SelectInput = ({
       name={fieldName}
       value={selected}
       size={size}
+      classNamePrefix="custom-select"
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/common/form/inputs.tsx:172]: react-select attaches this to its various components, which allows the tests to cleanly target specific elements.

File: clients/admin-ui/src/features/system/DescribeSystemStep.tsx [hunk 11]
```diff
@@ -65,9 +67,10 @@ const DescribeSystemStep = ({
         : defaultInitialValues,
     [passedInSystem]
   );
-  const [createSystem] = useCreateSystemMutation();
-  const [updateSystem] = useUpdateSystemMutation();
-  const [isLoading, setIsLoading] = useState(false);
+  const [createSystemMutationTrigger, createSystemMutationResult] =
+    useCreateSystemMutation();
+  const [updateSystemMutationTrigger, updateSystemMutationResult] =
+    useUpdateSystemMutation();
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/system/DescribeSystemStep.tsx:73]: Yes, the naming scheme of `<operation><Model>Mutation<Trigger|Result>` is verbose. But the more I encounter code where the API-calling function starts off as a simple name, then gets wrapped in handling logic, and so on, the more I think making it clear which one actually fires the request is worth the characters.

File: clients/admin-ui/src/features/system/form.ts [hunk 12]
```diff
@@ -1,8 +1,10 @@
+import { CustomFieldsFormValues } from "~/features/common/custom-fields";
 import { DEFAULT_ORGANIZATION_FIDES_KEY } from "~/features/organization";
 import { DataProtectionImpactAssessment, System } from "~/types/api";
 
 export interface FormValues
-  extends Omit<System, "data_protection_impact_assessment"> {
+  extends Omit<System, "data_protection_impact_assessment">,
+    CustomFieldsFormValues {
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/system/form.ts:7]: The benefit to putting the `CustomFieldsFormValues` into its own type is that these forms can then be explicit that they these properties as well. Previously the system and the taxonomy could end up including the custom fields in the JSON for an endpoint that doesn't expect it.

File: clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx [hunk 13]
```diff
@@ -59,27 +55,9 @@ const TaxonomyFormBase = ({
 
   const handleSubmit = async (newValues: FormValues) => {
     setFormError(null);
-    // parent_key and fides_keys are immutable
-    // parent_key also needs to be undefined, not an empty string, if there is no parent element
-    let payload: TaxonomyEntity;
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx:64]: This payload mutation that was mandatory for every resource type is now included in the hooks.

File: clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx [hunk 14]
```diff
@@ -146,14 +124,6 @@ const TaxonomyFormBase = ({
...
                 ))}
               {renderExtraFormFields ? renderExtraFormFields(values) : null}
-              {["data category", "data use", "data subject"].includes(
-                labels.fides_key.toLowerCase()
-              ) && (
-                <CustomFieldsList
-                  resourceId={initialValues.fides_key}
-                  resourceType={getResourceType(labels.fides_key)}
-                />
-              )}
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx:156]: This block now lives in `renderExtraFormFields` when appropriate for the resource type. This actually removes the need for any resource type checking.

File: clients/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx [hunk 15]
```diff
@@ -69,7 +71,6 @@ const TaxonomyTabContent = ({ useTaxonomy }: Props) => {
     return null;
   }, [data]);
 
-  const [entityToEdit, setEntityToEdit] = useState<TaxonomyEntity | null>(null);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx:72]: The hooks gain a lot of info by gaining control of this state. It was necessary for looking up custom fields by fides key, but I think a later refactor could make it even ore useful.

File: clients/admin-ui/src/features/taxonomy/hooks.tsx [hunk 16]
```diff
@@ -66,7 +78,33 @@ const transformTaxonomyBaseToInitialValues = (t: TaxonomyEntity) => ({
...
+  if (isCreate) {
+    const parentKey = parentKeyFromFidesKey(newValues.fides_key);
+    entity.parent_key = parentKey === "" ? undefined : parentKey;
+  } else {
+    entity.parent_key =
+      initialValues.parent_key === "" ? undefined : initialValues.parent_key;
+    entity.fides_key = initialValues.fides_key;
+  }
+
+  delete entity.definitionIdToCustomFieldValue;
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/hooks.tsx:99]: Note that the FormValues type now knows that this property exists (instead of just getting snuck in by Formik).

File: clients/admin-ui/src/features/taxonomy/hooks.tsx [hunk 17]
```diff
@@ -76,22 +114,71 @@ export const useDataCategory = (): TaxonomyHookData<DataCategory> => {
...
+
+  const handleCreate = async (
+    initialValues: FormValues,
+    newValues: FormValues
+  ) => {
+    const payload = transformBaseFormValuesToEntity(initialValues, newValues);
+    const result = await createDataCategoryMutationTrigger(payload);
+
+    if (customFields.isEnabled) {
+      await customFields.upsertCustomFields(newValues);
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/hooks.tsx:134]: Voilà, the form submission now has a single flow of async calls.

File: clients/admin-ui/src/features/taxonomy/hooks.tsx [hunk 18]
```diff
@@ -38,21 +41,30 @@ import {
...
-import { Labels, TaxonomyEntity } from "./types";
+import { FormValues, Labels, TaxonomyEntity } from "./types";
 
 export interface TaxonomyHookData<T extends TaxonomyEntity> {
   data?: TaxonomyEntity[];
   isLoading: boolean;
   labels: Labels;
-  handleCreate: (entity: T) => RTKResult<TaxonomyEntity>;
-  handleEdit: (entity: T) => RTKResult<TaxonomyEntity>;
+  resourceType?: ResourceTypes;
```
Comment (ssangervasi) [inline clients/admin-ui/src/features/taxonomy/hooks.tsx:57]: I added this so that components that use `TaxonomyHookData` could know what resource they're working with. However, it didn't turn out to be that useful outside of the body of the hook (so far).

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx (hunk 1 above)
Comment (chriscalhoun1974) [reply clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx:36]: Nice work encapsulating this logic using additional hooks and into its own drop down component.

Comment (chriscalhoun1974) [reply clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx:36]: Still don't think its possible to update the initial values in the CustomFieldsList component?

File: clients/admin-ui/src/features/common/custom-fields/helpers.ts (hunk 5 above)
Comment (chriscalhoun1974) [reply clients/admin-ui/src/features/common/custom-fields/helpers.ts:11]: Yes, this method can be deleted now given there are no references.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts (hunk 7 above)
Comment (chriscalhoun1974) [reply clients/admin-ui/src/features/common/custom-fields/hooks.ts:130]: You are referencing your comment on line 130?

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts (hunk 8 above)
Comment (chriscalhoun1974) [reply clients/admin-ui/src/features/common/custom-fields/hooks.ts:145]: The API does allow for an empty array to be submitted. However, I do understand about your point about deleting the custom field assignment.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts [hunk 19]
```diff
@@ -0,0 +1,191 @@
...
+
+        successAlert(
+          `Custom field(s) successfully saved and added to this ${resourceType} form.`
+        );
+      } catch (e) {
+        errorAlert(
+          `One or more custom fields have failed to save, please try again.`
+        );
+        // eslint-disable-next-line no-console
+        console.error(e);
```
Comment (chriscalhoun1974) [inline clients/admin-ui/src/features/common/custom-fields/hooks.ts:167]: Can you remove this console error statement?

**Review by chriscalhoun1974 — APPROVED** [review]
lgtm

File: clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts [hunk 20]
```diff
@@ -10,23 +10,48 @@ describe("Taxonomy management with Plus features", () => {
...
+  };
+  const RESOURCE_CHILD = {
+    label: "Biometric Data",
+    key: "user.biometric",
+  };
+
   const navigateToEditor = () => {
-    cy.getByTestId("accordion-item-User Data").click();
-    cy.getByTestId("item-Biometric Data")
+    cy.getByTestId(`accordion-item-${RESOURCE_PARENT.label}`).click();
```
Comment (allisonking) [inline clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts:27]: ah right, getting flashbacks of those recursive taxonomy accordion days 😭

File: clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts [hunk 21]
```diff
@@ -10,23 +10,48 @@ describe("Taxonomy management with Plus features", () => {
...
-      .within(() => {
-        cy.contains(optionText).click();
-      });
+    getSelectOptionList(selectorId).contains(optionText).click();
   };
 
+  const removeMultiValue = (selectorId: string, optionText: string) =>
+    getSelectValueContainer(selectorId)
+      .contains(optionText)
+      .siblings(".custom-select__multi-value__remove")
```
Comment (allisonking) [inline clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts:49]: oh nice this is a good way to do it

File: clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts [hunk 22]
```diff
@@ -149,4 +174,106 @@ describe("Taxonomy management with Plus features", () => {
...
+        "GET",
+        `/api/v1/plus/custom-metadata/custom-field/resource/${RESOURCE_CHILD.key}`,
+        {
+          fixture: "taxonomy/custom-metadata/custom-field/list.json",
+        }
+      ).as("getCustomFields");
+
+      navigateToEditor();
+
+      cy.wait([
```
Comment (allisonking) [inline clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts:213]: wow I didn't know you could do an array like this!

File: clients/admin-ui/src/features/common/form/inputs.tsx (hunk 10 above)
Comment (allisonking) [reply clients/admin-ui/src/features/common/form/inputs.tsx:172]: nice!

File: clients/admin-ui/src/features/taxonomy/hooks.tsx (hunk 16 above)
Comment (allisonking) [reply clients/admin-ui/src/features/taxonomy/hooks.tsx:99]: heh nice, I always felt a little too sneaky about that

**Review by allisonking — APPROVED** [review]
whew, nice job!!

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx [hunk 23]
```diff
@@ -0,0 +1,65 @@
...
+
+  return (
+    <CustomSelect
+      isClearable
+      isMulti={customFieldDefinition.field_type !== AllowedTypes.STRING}
+      label={label}
+      name={name}
+      options={options}
+      tooltip={tooltip}
+      defaultValue={customField?.value ?? ""}
```
[the remark this answers is not in the document]
Comment (ssangervasi) [reply clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx:62]: Yeah that's gonna be fun.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts (hunk 7 above)
Comment (ssangervasi) [reply clients/admin-ui/src/features/common/custom-fields/hooks.ts:130]: https://github.com/ethyca/fides/issues/2612

File: clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx (hunk 1 above)
Comment (ssangervasi) [reply clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx:36]: No, I think it would have to be higher up, to where Formik actually receives the prop, which I think means it needs to fit into the taxonomy hooks' methods.

File: clients/admin-ui/src/features/common/custom-fields/hooks.ts (hunk 19 above)
Comment (ssangervasi) [reply clients/admin-ui/src/features/common/custom-fields/hooks.ts:167]: I was thinking it could be helpful even after merge in case we encounter another API incompatibility.
