### PR TITLE
fix issue with unsaved changes modal

### LINKED ISSUE #4006: Unsaved changes modal pops up at incorrect time
Steps to reproduce:

1. create a system
2. click on data use tab
3. click back to system tab
4. click on data use tab again
5. notice that the unsaved changes modal pops up even though the form hasn't changed

### PR DESCRIPTION
**Pull request by TheAndrewJackson**
Closes #4006 

### Code Changes

* [ ] Fix regression in form values that caused the unsaved changes modal to show up incorrectly
* [ ] Refactor the system info form to use the newer more generalized unsaved changes modal

### Steps to Confirm

* [ ] run admin ui and fides server
* [ ] create a system
* [ ] click on data use tab
* [ ] click back to system tab
* [ ] click on data use tab again
* [ ] verify that the unsaved changes modal didn't pop up

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CODE REVIEW

File: clients/admin-ui/src/features/system/form.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ export const defaultInitialValues: FormValues = {
   data_security_practices: "",
   privacy_declarations: [],
   data_stewards: "",
+  dpo: "",
```
Comment (TheAndrewJackson) [inline clients/admin-ui/src/features/system/form.ts:42]: these fields are what was causing the issue

**Review by allisonking — APPROVED** [review]
nice, works great! glad to finally consolidate on one approach for these unsaved forms. 

we could consider closing this: https://github.com/ethyca/fides/issues/2631

I guess we don't handle reroutes yet, but I don't know if anyone ever asked for that :)

**Comment by TheAndrewJackson** [comment]
@allisonking I'll go ahead an close #2361. If anyone asks for it we can make a new ticket
