### PR TITLE
1443 unverified consent requests

### LINKED ISSUE #1443: Support running unverified consent requests when testing
### Description

When we implemented consent requests we (reasonably) decided that it was unsafe to allow arbitrary API requests to create/read consent data without verifying the identity of the caller. This ensures that Fides is secure-by-default, which is nice.

However, this type of requirement unfortunately conflicts with making Fides easy to test, since it means we're required to configure Mailgun and supply verification codes for anything related to consent requests. This makes writing automated E2E tests that exercise the consent functionality complicated and slow!

For the privacy request flow, this is fully optional though, and works great. I can test out creating, approving, and executing privacy requests without ever configuring an email integration - and therefore I can also write automated tests that do this E2E.

Therefore the ask here is pretty simple: let's make **identity verification optional for consent requests to be consistent with the privacy request flow**.

### Requirements

* MUST update the Fides webserver to support unverified consent requests
* MUST update the Fides privacy center to support unverified consent requests
* MUST support enforcing identity verification on both privacy requests & consent requests when the server is configured to do so ( (`subject_identity_verification_required = false`)

### LINKED ISSUE #1525: Fix failing`test_match_route` unit test
### Bug Description

In the last few days, this unit test has mysteriously started failing (for example: https://github.com/ethyca/fides/actions/runs/3294161562/jobs/5431682500#step:6:700)

We've temporarily xfail'd the test to skip it, but should revert that and either fix the test assertion or the underlying code.

#### Steps to Reproduce

1. Remove the xfail mark from tests/ctl/api/test_ui.py
1. Run `pytest`

### Expected behavior

Test should pass!

### Additional context

The root issue here appears to be that the underlying `match_route` function doesn't handle cases of multiple matching routes in a fully deterministic way.

### PR DESCRIPTION
**Pull request by TheAndrewJackson**
Closes #1443
Closes #1525

### Code Changes

* Deleted duplicated component file
* Updated privacy center to support unverified consent requests
* Updated backend to allow unverified consent requests
* Refactored unit tests to factor in the new changes
* Added new unit tests for the unverified get route

### Steps to Confirm

* [ ] Run fides with `subject_identity_verification_required` set to `false`
* [ ] Run privacy center
* [ ] Do a consent request and get redirected to the consent page
* [ ] Update preferences
* [ ] Do another consent request and see the updated preferences

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [x] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

Update fides and the privacy center to support unverified consent requests. This will allow for easier setup and development.

https://user-images.githubusercontent.com/17103888/196696745-19308251-2524-4588-8725-e7361f94e244.mov

### CODE REVIEW

File: clients/privacy-center/pages/consent.tsx [hunk 1]
```diff
@@ -26,10 +26,10 @@ const Consent: NextPage = () => {
   const router = useRouter();
 
   useEffect(() => {
-    if (!consentRequestId || !verificationCode) {
+    if (!consentRequestId) {
       router.push("/");
     }
-  }, [consentRequestId, verificationCode, router]);
+  }, [consentRequestId, router]);
```
Comment (allisonking) [inline clients/privacy-center/pages/consent.tsx:32]: I don't know the expected flow of this too well, but I wonder if there is a place where we need to clear out stale values? 

or perhaps instead of local storage, we should use query parameters? though that would only work if this page and the home page are the only places that use these codes/ids. probably out of the scope of this PR tho

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx [hunk 2]
```diff
@@ -21,9 +21,8 @@ export const useConsentRequestModal = () => {
   );
 
   const successHandler = useCallback(() => {
-    setConsentRequestId(consentRequestId);
     router.push("consent");
```
Comment (allisonking) [inline clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:24]: a toast here might be nice. I think they do persist across route changes—if you trigger a toast on this page https://chakra-ui.com/docs/components/toast and then click on another link, the toast will still stick around)

**Review by allisonking — COMMENTED** [review]
awesome python tests! just a few comments, but for the most part looks good and worked on my machine 👍

File: src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py [hunk 3]
```diff
@@ -137,6 +135,36 @@ def consent_request_verify(
...
+    if CONFIG.execution.subject_identity_verification_required:
+        raise HTTPException(
+            status_code=400,
+            detail="Retrieving consent preferences without identity verification is "
+            "only supported with subject_identity_verification_required "
+            "turned off.",
+        )
+
+    provided_identity = _get_consent_request_and_provided_identity(
+        db=db, consent_request_id=consent_request_id, verification_code=""
```
[the remark this answers is not in the document]
Comment (TheAndrewJackson) [reply src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py:157]: I agree. Updated!

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx [hunk 4]
```diff
@@ -74,12 +76,12 @@ const useConsentRequestForm = ({
         const data = await response.json();
```
[the remark this answers is not in the document]
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx:76]: That does make more sense. I put that check in the top level `useEffect` initially and never refactored it back out later. I'll update it so the consent id check is closer to the actual logic it effects

File: clients/privacy-center/pages/consent.tsx (hunk 1 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/pages/consent.tsx:32]: There probably is a better way to do this. I think the privacy center will need a refactor to use RTK query at some in the near future. Maybe those values could live in the redux store?

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx (hunk 2 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:24]: ohh nice! I specifically didn't use a toast because of the page change. I didn't know they persisted across pages

File: src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py [hunk 5]
```diff
@@ -137,6 +135,36 @@ def consent_request_verify(
     return _prepare_consent_preferences(db, provided_identity)
 
 
+@router.get(
+    CONSENT_REQUEST_PREFERENCES_WITH_ID,
+    status_code=HTTP_200_OK,
```
[the remark this answers is not in the document]
Comment (TheAndrewJackson) [reply src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py:140]: The `_get_consent_request_and_provided_identity` function inside this route handles raising the 400 and 404 error codes in a consent request doesn't exist.

If the consent request exists and the user has no consent preferences the `_prepare_consent_preferences` functions returns `None` for the list of preferences. I _think_ everything is handled. Does that make sense?

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx (hunk 2 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:24]: I'm running into some weird issues getting the toast working. Are you okay with it being addressed in a follow up?

Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:24]: The issue is react no-op errors. I'm not quite sure what's causing the no-op

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx:76]: The change is pushed now. If things are still a little confusing maybe I can write out the excepted flow

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx (hunk 2 above)
Comment (allisonking) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:24]: yeah no problem! let's do a follow up issue since iirc there are a few places that might be nice to have a toast

File: src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (allisonking) [reply src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py:140]: ah yeah what I meant here was more docs related: if you go to localhost:8080/docs, and then go to the entry for `consent`/GET, it only shows possible return statuses of 200 and 422 (not 400 or 404). here's an example of another endpoint that does it: https://github.com/ethyca/fides/blob/1443_unverified_consent_requests/src/fides/api/ctl/routes/datamap.py/#L72-L83

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (allisonking) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx:76]: it looks like the changes you made were to `consent.tsx` but the function I found confusing was the `onSubmit` func in `ConsentRequestForm.tsx`. lemme know if I'm missing something about how those two are related!

**Comment by TheAndrewJackson** [comment]
@allisonking I think I've addressed all the PR feedback. Now I'm getting some test failures that seems unrelated to my code changes in the ctl test suite. I tested this locally on my machine and the tests failed on main too. I think this may be good to merge if the code looks good to you but it would be good to confirm that the tests fail for someone else too.

**Comment by seanpreston** [comment]
It looks like the modal text says "we will email you..."

image (3)

however Fides won't email the user currently. Can we correct that?

**Comment by TheAndrewJackson** [comment]
@seanpreston good catch. Yes, I'll update that now

**Comment by NevilleS** [comment]
@TheAndrewJackson I can try this out using `nox -s test_env` when you're ready, too. You'll notice that I disabled consent requests on `main` in a recent commit so that the privacy center would work by default.

**Comment by TheAndrewJackson** [comment]
@NevilleS This is ready to test with `nox -s test_env` now

**Comment by NevilleS** [comment]
@TheAndrewJackson I pulled your branch and tried testing this out and it wasn't working for me. I get a 404 error for `http://localhost:8080/api/v1/consent-request//preferences` in the Javascript console:
image

Steps to reproduce:
1. `git pull 1443_unverified_consent_requests`
2. Ensure that `.fides/fides.toml` has `subject_identity_verification_required` set to `false`
3. Edit `clients/privacy-center/config/config.json` and set `"includeConsent": true`
4. Run `nox -s test_env`
5. Open privacy center at http://localhost:3001/
6. Click "Manage my consent" and provide my email
7. Nothing happens. Observe the Javascript error

Two observations here:
* It seems to be calling the API but not actually providing the email I gave it
* There is no visible error message in the UI; we should catch any server error like this and show an error toast

Let me know if you need help repro'ing this or if I've missed something.

**Comment by TheAndrewJackson** [comment]
@NevilleS Thanks for taking a look. I followed those repo steps and everything worked for me. I thought I fixed the issue that you're seeing. Is the most recent local commit for this branch `Fix logic issue from refactor` on your machine?

An error toast would be help. Do you want it included in this PR or in a follow up ticket?

**Comment by NevilleS** [comment]
Let's add the error toast now, or it'll just be a bug that we find later!

Meanwhile I'll double-check my repo...

**Comment by NevilleS** [comment]
Re-tested with the latest commit and it looks good now 👍 

My little design/quality asks are:
* add error toast for server errors
* add success toast for after you save, like "Your consent preferences have been saved"

Otherwise LGTM, thanks!

**Comment by NevilleS** [comment]
Oh, and one more thing @TheAndrewJackson - since you've done the work here to allow consent requests to be testable by default (i.e. without any secrets!), I've gone ahead and pushed a small commit to your branch to enable them in the privacy center again and give a few semi-realistic examples. That way, consent requests will be available in the test env once this merges.

Cheers!

**Comment by ThomasLaPiana** [comment]
love to see that `test_env` usage :D

**Comment by TheAndrewJackson** [comment]
@NevilleS The project has been updated to use toasts for everything now 🎉  The original toasts were actually a hacky workaround needed due to a config issue in the project. I removed the workaround now that everything is using actual toasts. 

Here are some examples of success toasts.

https://user-images.githubusercontent.com/17103888/197212688-7a35f08d-bc77-4520-a12a-3593a4487e5e.mov

https://user-images.githubusercontent.com/17103888/197212710-9c3664c3-ebd5-4fd9-b531-9dd6afd3951f.mov


https://user-images.githubusercontent.com/17103888/197212738-2632acd4-41f2-4eb4-865c-2c73d5388c21.mov


Users are now told if the privacy center had an issue getting the config (ex: backend isn't running)

https://user-images.githubusercontent.com/17103888/197212863-f2fe0517-5718-4a51-a499-6721d165edbc.mov

**Comment by NevilleS** [comment]
Thanks @TheAndrewJackson, those toasts are a great improvement. I've pushed a commit to (try) to fix the failing test as well - this should close #1525 as well (updated the description)

**Comment by TheAndrewJackson** [comment]
@NevilleS I ran into a small test failure on my machine. It was returning `multimatch/[second].html`  instead of `multimatch/[first].html`. This is because they both generate the same regex pattern and the second file overwrites the first while the route dict is being generated. I did a quick test and tried to build a nextjs website with two dynamic pages like that in the same directory and it returned this error `Error: You cannot use different slug names for the same dynamic path ('id' !== 'test')`. I think it's safe to remove the `multimatch/[second].html`  file from the test data because nextjs prevents builds like that from happening. Removing that file made the test pass.

I'm going to remove the extra test file and if the CI passes I'll merge it.

File: clients/privacy-center/common/toast-options.ts [hunk 6]
```diff
@@ -0,0 +1,21 @@
+import {UseToastOptions} from "@chakra-ui/react";
```
Comment (allisonking) [inline clients/privacy-center/common/toast-options.ts:1]: surprised prettier didn't make this `{ UseToastOptions }`

File: clients/privacy-center/common/toast-options.ts [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+
+const BaseToastOptions: UseToastOptions = {
+    position: "top",
+    duration: 5500
+}
```
Comment (allisonking) [inline clients/privacy-center/common/toast-options.ts:6]: FYI there's this helper file in admin-ui which I plan to pull into fidesui soon which does similar stuff as this one https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/features/common/toast.tsx

I do think it's nice the way you have the actual error in this file though, should make it easy to import and stay consistent with our copy! I'll have to noodle on it some more, but I might prefer the way you have here with just exporting the ToastOptions instead of what is in admin-ui of exporting a function 👍

File: clients/privacy-center/components/modals/VerificationForm.tsx [hunk 8]
```diff
@@ -12,36 +12,36 @@ import {
...
 import { Headers } from "headers-polyfill";
-import type { AlertState } from "../../types/AlertState";
-import { ModalViews, VerificationType } from "./types";
-import { addCommonHeaders } from "../../common/CommonHeaders";
-import { useLocalStorage } from "../../common/hooks";
+import { addCommonHeaders } from "~/common/CommonHeaders";
+import { useLocalStorage } from "~/common/hooks";
 
-import { hostUrl } from "../../constants";
+import { hostUrl } from "~/constants";
```
Comment (allisonking) [inline clients/privacy-center/components/modals/VerificationForm.tsx:25]: heh thanks for changing these to `~/`, I do like it a lot more 😄

File: clients/privacy-center/components/modals/VerificationForm.tsx [hunk 9]
```diff
@@ -86,13 +91,19 @@ const useVerificationForm = ({
         const data = await response.json();
 
         if (!response.ok) {
-          handleError(data?.detail);
+          handleError({
+            title: "An error occurred while verifying your identity",
+            error: data?.detail,
```
Comment (allisonking) [inline clients/privacy-center/components/modals/VerificationForm.tsx:96]: should we still have the `fallbackMessage` here?

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx [hunk 10]
```diff
@@ -67,33 +75,31 @@ const useConsentRequestForm = ({
...
+          });
           return;
         }
 
-        const data = await response.json();
-
-        if (!isVerificationRequired && data.consent_request_id) {
-          setConsentRequestId(data.consent_request_id);
-          successHandler();
+        if (!data.consent_request_id) {
```
Comment (allisonking) [inline clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx:87]: woot thanks for doing this! easier to follow now 😄

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx [hunk 11]
```diff
@@ -91,7 +86,6 @@ export const ConsentRequestModal: React.FC<ConsentRequestModalProps> = ({
       <VerificationForm
         isOpen={isOpen}
         onClose={onClose}
-        setAlert={setAlert}
```
Comment (allisonking) [inline clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:94]: ahhh I love that you were able to clean this up 💯

File: clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx [hunk 12]
```diff
@@ -66,10 +66,17 @@ const usePrivacyRequestForm = ({
...
+      const handleError = ({
+        title,
+        error,
+      }: {
+        title: string;
+        error?: any;
+      }) => {
+        toast({
+          title,
+          description: error,
```
Comment (allisonking) [inline clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx:78]: I wonder if it would make sense to do an `error || fallbackErrorMessage` here? so the other places that call this func below don't have to pass in the same "an unhandled error" occurred msg

File: clients/privacy-center/pages/_app.tsx [hunk 13]
```diff
@@ -1,6 +1,12 @@
 import type { AppProps } from "next/app";
 import { SessionProvider } from "next-auth/react";
-import { FidesProvider } from "@fidesui/react";
+/*
+ * This import needed to be updated to '@chakra-ui/react' from "@fidesui/react".
+ * Under the hood fidesui is importing from "@chakra-ui/provider" instead "chakra-ui/react".
+ * This causes issues with toasts because it doesn't set up everything required for them.
+ * Solution found here https://github.com/chakra-ui/chakra-ui/issues/5839#issuecomment-1266493711
+ * */
+import { ChakraProvider } from "@chakra-ui/react";
```
Comment (allisonking) [inline clients/privacy-center/pages/_app.tsx:9]: great find + comment! it looks like that's how we do it in `admin-ui` too

File: src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py [hunk 14]
```diff
@@ -139,6 +139,27 @@ def consent_request_verify(
...
+                },
+                {
+                    "data_use": "improve",
+                    "data_use_description": "We may use some of your personal information to collect analytics about "
+                    "how you use our products & services, in order to improve our service.",
+                    "opt_in": False,
+                },
+            ]
+        },
+        HTTP_404_NOT_FOUND: {"detail": "Consent request not found"},
```
Comment (allisonking) [inline src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py:161]: I think there also needs to be a `400` error code here which occurs when `subject_identity_verification_required` is turned off?

**Review by allisonking — COMMENTED** [review]
Looking good! I think there's just one additional docs response that should be added. everything else is just nits

**Review by NevilleS — APPROVED** [review]
LGTM now, thanks for the extra polish based on my QA testing 👍

File: src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py (hunk 14 above)
Comment (TheAndrewJackson) [reply src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py:161]: Good catch! It's fixed now.

File: clients/privacy-center/pages/_app.tsx (hunk 13 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/pages/_app.tsx:9]: Maybe we should update this in `fidesui`? Either that or get rid of the aliasing types altogether. My guess is someone ran into the same problem I did in the `admin-ui` and did exactly what I did.

File: clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx (hunk 11 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/consent-request-modal/ConsentRequestModal.tsx:94]: It felt good to remove all that code!

File: clients/privacy-center/components/modals/VerificationForm.tsx (hunk 9 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/VerificationForm.tsx:96]: I think it's okay to leave it out here. The title is very similar to the original `fallbackMessage`. I'm using the error field here for more specific responses from the backend.

The previous version wasn't doing a title and error message at the same time. So the title is acting as a fallback already and the error message is only used if more data is provided from the backend.

File: clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx (hunk 12 above)
Comment (TheAndrewJackson) [reply clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx:78]: Piggy backing off of my comment from another toast related feedback.

> I think it's okay to leave it out here. The title is very similar to the original fallbackMessage. I'm using the error field here for more specific responses from the backend. 
 The previous version wasn't doing a title and error message at the same time. So the title is acting as a fallback already and the error message is only used if more data is provided from the backend.

Since the title is already acting as a fallback message and there aren't useful messages being return from the backend I left the error field blank.


And the titles themselves are very similiar but not quite the same. One says

> error occurred while processing

while the other says

> error occurred while creating

If this is a confusing pattern to use for the toast messages maybe we can interate on it in the future once the toast helper is merged into fidesui?

**Review by allisonking — APPROVED** [review]
🚀
