### PR TITLE
Store fides_consent cookie on the root domain of the Privacy Center

### LINKED ISSUE #2070: Fides consent cookie should be written to the root domain
### Bug Description

When testing out the `fides_consent` cookie on a sample site (privacy.j1407b.com) I noticed that the cookie isn't being set to the root:
image

This means that you can't read this cookie from other subdomains on the same root, which is a very common pattern. We need to be able to have a deployment like:
* example.com (main site)
* privacy.example.com (privacy center)

And have the cookies set by privacy.example.com accessible from the main, parent domain.

#### Steps to Reproduce

1. Run a privacy center on a subdomain
2. Toggle any consent settings to generate the `fides_consent` cookie
3. Inspect the `fides_consent` cookie in the developer console

### Expected behavior

`fides_consent` cookie should be set to the root domain (e.g. `.j1407b.com` in this case)

### PR DESCRIPTION
**Pull request by NevilleS**
Closes #2070

### Code Changes

* [X] Calculate the root domain (based on `window.location`)
* [X] Save the cookie using the root domain

### Steps to Confirm

* [X] Ran `nox -s test_env` and confirmed cookie still writes out unchanged
* [ ] Deploy privacy center to a subdomain and test

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [x] documentation complete, PR opened in [fidesdocs](https://github.com/ethyca/fidesdocs)
  * [x] documentation issue created in [fidesdocs](https://github.com/ethyca/fidesdocs)
* [x] Issue Requirements are Met
* [X] Relevant Follow-Up Issues Created: https://github.com/ethyca/fides/issues/2072
* [x] Update `CHANGELOG.md`

### Description Of Changes

This has one major issue, which is that it'll only work for "normal" TLDs like ".com", ".co", etc., but will calculate the root domain incorrectly for sites that use second-level domains like "example.co.uk" or "example.co.jp", etc.

### CODE REVIEW

File: clients/privacy-center/packages/fides-consent/src/lib/cookie.ts [hunk 1]
```diff
@@ -49,12 +49,21 @@ export const setConsentCookie = (cookieKeyConsent: CookieKeyConsent) => {
     return;
   }
 
+  // Calculate the root domain by taking (up to) the last two parts of the domain:
+  //   privacy.example.com -> example.com
+  //   example.com -> example.com
+  //   localhost -> localhost
+  //
+  // TODO: This won't second-level domains like co.uk:
+  //   privacy.example.co.uk -> co.uk # ERROR
```
Comment (NevilleS) [inline clients/privacy-center/packages/fides-consent/src/lib/cookie.ts:58]: Opened https://github.com/ethyca/fides/issues/2072 for this

**Review by Kelsey-Ethyca — APPROVED** [review]
